// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/arcade": {
    params: {};
  };
  "/tasks/:taskId": {
    params: {
      "taskId": string;
    };
  };
  "/api/logs/:taskId": {
    params: {
      "taskId": string;
    };
  };
  "/api/logs/:taskId/stream": {
    params: {
      "taskId": string;
    };
  };
  "/api/tasks/:taskId/stop": {
    params: {
      "taskId": string;
    };
  };
  "/api/tasks/:taskId/comments": {
    params: {
      "taskId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/arcade" | "/tasks/:taskId" | "/api/logs/:taskId" | "/api/logs/:taskId/stream" | "/api/tasks/:taskId/stop" | "/api/tasks/:taskId/comments";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/arcade.tsx": {
    id: "routes/arcade";
    page: "/arcade";
  };
  "routes/tasks.$taskId.tsx": {
    id: "routes/tasks.$taskId";
    page: "/tasks/:taskId";
  };
  "routes/api.logs.$taskId.ts": {
    id: "routes/api.logs.$taskId";
    page: "/api/logs/:taskId";
  };
  "routes/api.logs.$taskId.stream.ts": {
    id: "routes/api.logs.$taskId.stream";
    page: "/api/logs/:taskId/stream";
  };
  "routes/api.tasks.$taskId.stop.ts": {
    id: "routes/api.tasks.$taskId.stop";
    page: "/api/tasks/:taskId/stop";
  };
  "routes/api.tasks.$taskId.comments.ts": {
    id: "routes/api.tasks.$taskId.comments";
    page: "/api/tasks/:taskId/comments";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/arcade": typeof import("./app/routes/arcade.tsx");
  "routes/tasks.$taskId": typeof import("./app/routes/tasks.$taskId.tsx");
  "routes/api.logs.$taskId": typeof import("./app/routes/api.logs.$taskId.ts");
  "routes/api.logs.$taskId.stream": typeof import("./app/routes/api.logs.$taskId.stream.ts");
  "routes/api.tasks.$taskId.stop": typeof import("./app/routes/api.tasks.$taskId.stop.ts");
  "routes/api.tasks.$taskId.comments": typeof import("./app/routes/api.tasks.$taskId.comments.ts");
};